[project]
name = "pyfend-cli"
version = "0.1.0"
description = "Command-line interface for PyFend"
readme = "README.md"
authors = [
    { name = "Raymond Frans Dodi Situmorang", email = "raymondsitumorang17@gmail.com" },
    { name = "Wilson Angelie Tan", email = "wilsonangelietann@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.3",
    "pyfend==0.1.0",
    "questionary>=2.1.1",
]
license = "MIT"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Repository = "https://github.com/PyFend/PyFend"
Issues = "https://github.com/PyFend/PyFend/issues"

[project.scripts]
pyfend = "pyfend.cli.__main__:main"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyfend.cli"]
package-dir = { "pyfend.cli" = "." }

[tool.setuptools.package-data]
"pyfend.cli" = ["py.typed"]
